# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Short But Great Stories"
description: > # this means to ignore newlines until "email:"
   Independent writing project, but I am dependent on the soul of writing.

email: viniciussouza31122002@gmail.com
#blog logo
logo: "/assets/images/SBGS_logo_4.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/sbgs_cover_2.jpg"

name: 'Vinicius de Souza Marcon'
author: 'Vinicius de Souza Marcon'
author_image: "/assets/images/profile_picture.jpeg"

paginate:	5

url: "http://vsmarcon.github.io" # the base hostname & protocol for your site
baseurl: "/ENShortButGreatStories"
#used to display twitter cards
#twitter_handle: '@dirkfabisch'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	instagram
    url:	https://instagram.com/_marc0n
    desc: Follow me on Instagram
    
    # share_url: http://twitter.com/share
    # share_title: ?text=
    # share_link: "&amp;url="
  - icon:	instagram
    url:	https://instagram.com/10poesias01
    desc: Follow my 'instapoetry' page
  - icon:	mug-hot
    url:	https://www.buymeacoffee.com/sbgstories/
    desc: Support the page
  
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="
